/** Cloudflare Pages Function — secure dual-write for rank & rent leads. */
const SITE_DOMAIN = 'panneau-solaire-alpes-maritimes.fr';
const SITE_NICHE = 'panneau-solaire';
const DEPT_CODE = '06';
const CP_PATTERN = /^06\d{3}$/;
const SUPABASE_URL = 'https://nhmvgsrwhjsjnpncpiaj.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5obXZnc3J3aGpzam5wbmNwaWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5OTY0NjQsImV4cCI6MjA4MzU3MjQ2NH0.qpG5CJDNa53BB7ZpDy414GL3hmb51omxqPrnrrd7O6I';
const VUD_API_KEY = '17695301406978e31c715766978e31c715ae';
const VUD_PING_URL = 'https://www.viteundevis.com/api/ping.php';
const VUD_LEAD_URL = 'https://www.viteundevis.com/api/get.php';
const MAX_BODY_BYTES = 16_384;
const POSTAL_CITIES = {
  '06000':['nice'],'06100':['nice'],'06200':['nice'],'06160':['antibes'],'06600':['antibes'],'06150':['cannes'],'06400':['cannes'],'06800':['cagnes sur mer'],'06130':['grasse'],'06520':['grasse'],'06110':['le cannet'],'06700':['saint laurent du var'],'06500':['menton','gorbio','castillon'],'06220':['vallauris'],'06210':['mandelieu la napoule'],'06140':['vence','tourrettes sur loup'],'06250':['mougins'],'06190':['roquebrune cap martin'],'06560':['valbonne'],'06410':['biot'],'06270':['villeneuve loubet'],'06480':['la colle sur loup'],'06530':['peymeinade','saint cezaire sur siagne'],'06230':['villefranche sur mer'],'06240':['beausoleil'],'06340':['la trinite','drap'],'06390':['contes','chateauneuf villevieille','coaraze','berre les alpes'],'06510':['carros','gattieres','le broc'],'06670':['levens','castagniers','colomars','saint martin du var','saint blaise'],'06580':['pegomas'],'06550':['la roquette sur siagne'],'06730':['saint andre de la roche'],'06610':['la gaude'],'06650':['opio','le rouret'],'06690':['tourrette levens'],'06740':['chateauneuf grasse'],'06570':['saint paul de vence'],'06360':['eze'],'06320':['cap d ail','la turbie'],'06380':['sospel'],'06540':['breil sur roya'],'06660':['auron','saint etienne de tinee'],'06460':['saint vallier de thiey'],'06330':['roquefort les pins'],'06620':['le bar sur loup'],'06810':['auribeau sur siagne'],'06430':['tende'],'06950':['falicon'],'06790':['aspremont'],'06640':['saint jeannet'],'06710':['villars sur var'],'06420':['roubion'],'06830':['bonson'],'06440':['blausasc','peille','l escarene','luceram']
};
const json = (body, status = 200, origin = '') => new Response(JSON.stringify(body), { status, headers: { 'Content-Type':'application/json; charset=utf-8', 'Cache-Control':'no-store', ...cors(origin) } });
const cors = (origin) => ({ 'Access-Control-Allow-Origin': origin || `https://${SITE_DOMAIN}`, 'Access-Control-Allow-Methods':'POST, OPTIONS', 'Access-Control-Allow-Headers':'Content-Type', Vary:'Origin' });
const normalized = (value = '') => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
const normalPhone = (value = '') => { let digits = String(value).replace(/\D/g,''); if (digits.startsWith('0033')) digits = `0${digits.slice(4)}`; if (digits.startsWith('33') && digits.length === 11) digits = `0${digits.slice(2)}`; return /^0[1-9]\d{8}$/.test(digits) ? digits : null; };
const withTimeout = async (url, options, fetcher) => { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 10_000); try { return await fetcher(url, { ...options, signal: controller.signal }); } finally { clearTimeout(timeout); } };
const isAllowedOrigin = (origin, env) => { if (origin === `https://${SITE_DOMAIN}` || origin === `https://www.${SITE_DOMAIN}`) return true; return Boolean(env?.ALLOW_LOCAL_ORIGIN === 'true' && /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin)); };
const sbHeaders = (env, extra = {}) => { const key = env.SUPABASE_ANON_KEY || SUPABASE_ANON_KEY; return { 'Content-Type':'application/json', apikey:key, Authorization:`Bearer ${key}`, ...extra }; };
const extractVud = (data) => ({ code:String(data?.code_retour?.[0]?.code ?? data?.code ?? ''), devisId:data?.devis_data?.devis_id || null, devisHash:data?.devis_data?.devis_hash || null });

export async function handleLead(context, fetcher = fetch) {
  const { request, env = {} } = context; const origin = request.headers.get('Origin') || '';
  if (!isAllowedOrigin(origin, env)) return json({ success:false, message:'Origine non autorisée.' }, 403, origin);
  const supabaseUrl = env.SUPABASE_URL || SUPABASE_URL;
  const supabaseAnonKey = env.SUPABASE_ANON_KEY || SUPABASE_ANON_KEY;
  const vudApiKey = env.VUD_API_KEY || VUD_API_KEY;
  if (!supabaseUrl || !supabaseAnonKey || !vudApiKey) return json({ success:false, message:'Le service de devis n’est pas configuré.' }, 503, origin);
  if (!request.headers.get('Content-Type')?.toLowerCase().includes('application/json')) return json({ success:false, message:'Format de requête invalide.' }, 415, origin);
  const contentLength = Number(request.headers.get('Content-Length') || 0); if (contentLength > MAX_BODY_BYTES) return json({ success:false, message:'Requête trop volumineuse.' }, 413, origin);
  let raw; try { const text = await request.text(); if (new TextEncoder().encode(text).byteLength > MAX_BODY_BYTES) return json({ success:false,message:'Requête trop volumineuse.' },413,origin); raw = JSON.parse(text); } catch { return json({ success:false, message:'Données JSON invalides.' }, 400, origin); }
  const errors = []; const required = ['nom','prenom','email','adresse','cp','ville','submissionId'];
  if (raw.website) errors.push('Soumission invalide.'); required.forEach((key) => { if (!String(raw[key] || '').trim()) errors.push(`${key} requis.`); });
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(raw.email || ''))) errors.push('E-mail invalide.');
  if (String(raw.nom || '').trim().length < 2 || String(raw.prenom || '').trim().length < 2) errors.push('Nom et prénom requis.');
  if (String(raw.adresse || '').trim().length < 5) errors.push('Adresse complète requise.');
  if (!CP_PATTERN.test(String(raw.cp || ''))) errors.push('Le projet doit être situé dans les Alpes-Maritimes (06).');
  const phone = normalPhone(raw.tel); if (!phone) errors.push('Téléphone français invalide.');
  if (raw.consent !== true) errors.push('Le consentement explicite est requis.');
  const allowedCities = POSTAL_CITIES[String(raw.cp)] || []; if (allowedCities.length && !allowedCities.includes(normalized(raw.ville))) errors.push('La commune ne correspond pas au code postal indiqué.');
  if (String(raw.submissionId).length < 12 || String(raw.submissionId).length > 128) errors.push('Identifiant de soumission invalide.');
  if (errors.length) return json({ success:false, errors, message:'Veuillez corriger les champs signalés.' }, 400, origin);
  const submissionId = String(raw.submissionId); const catId = 37; const catName = 'Panneaux photovoltaïques';
  const description = `Projet ${raw.projectType || catName} à ${raw.ville} (${raw.cp}). Puissance envisagée : ${raw.powerNeed || 'à étudier'}. Consommation : ${raw.consumption || 'non renseignée'}. Délai : ${raw.delais === '1' ? 'dès que possible' : raw.delais === '3' ? 'plus de 3 mois' : 'dans les 3 mois'}.`;
  const base = supabaseUrl.replace(/\/$/,'');
  try {
    const duplicate = await withTimeout(`${base}/rest/v1/rank_rent_leads?submission_id=eq.${encodeURIComponent(submissionId)}&select=id,vud_status,vud_devis_id`, { headers:sbHeaders(env) }, fetcher);
    if (!duplicate.ok) return json({ success:false, message:'Votre demande ne peut pas être sécurisée pour le moment.' }, 503, origin);
    const previous = await duplicate.json(); if (previous?.length) return json({ success:true, status:previous[0].vud_status || 'captured', duplicate:true, devisId:previous[0].vud_devis_id || null }, 200, origin);
  } catch { return json({ success:false, message:'Le service de devis est temporairement indisponible.' }, 503, origin); }
  const payload = { source_site:SITE_DOMAIN, niche:SITE_NICHE, nom:String(raw.nom).trim(), prenom:String(raw.prenom).trim(), email:String(raw.email).trim().toLowerCase(), telephone:phone, adresse:String(raw.adresse).trim(), ville:String(raw.ville).trim(), code_postal:String(raw.cp), departement:DEPT_CODE, cat_id:catId, cat_name:catName, type_bien:String(raw.typeBien || '1'), situation:String(raw.situation || '1'), chauffage_actuel:String(raw.projectType || ''), delais:String(raw.delais || '2'), description, page_url:String(raw.pageUrl || `https://${SITE_DOMAIN}`).slice(0,500), ip_address:request.headers.get('CF-Connecting-IP') || null, user_agent:(request.headers.get('User-Agent') || '').slice(0,500), submission_id:submissionId, consent_at:new Date().toISOString(), vud_status:'pending' };
  let lead; try { const saved = await withTimeout(`${base}/rest/v1/rank_rent_leads`, { method:'POST', headers:sbHeaders(env,{Prefer:'return=representation'}), body:JSON.stringify(payload) }, fetcher); if (!saved.ok) return json({ success:false, message:'Votre demande n’a pas pu être enregistrée. Réessayez dans quelques instants.' }, 502, origin); lead = (await saved.json())?.[0]; if (!lead?.id) throw new Error('No lead id'); } catch { return json({ success:false, message:'Votre demande n’a pas pu être enregistrée. Réessayez dans quelques instants.' }, 502, origin); }
  const patch = async (data) => { try { await withTimeout(`${base}/rest/v1/rank_rent_leads?id=eq.${encodeURIComponent(lead.id)}`, { method:'PATCH',headers:sbHeaders(env),body:JSON.stringify({ ...data,updated_at:new Date().toISOString() }) },fetcher); } catch {} };
  let ping; try { const body = new URLSearchParams({token:vudApiKey,cat_id:String(catId),code_postal:String(raw.cp),pays:'fr',description,cpl_mini:'0'}); const response = await withTimeout(VUD_PING_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body},fetcher); if (!response.ok) throw new Error('Ping HTTP'); ping = await response.json(); } catch { await patch({vud_status:'ping_error'}); return json({success:true,status:'ping_error',message:'Votre demande est enregistrée. La disponibilité des installateurs est en cours de vérification.'},202,origin); }
  const accepted = Number(ping?.accept) === 1 && Number(ping?.recommande ?? 1) === 1; if (!accepted) { await patch({vud_status:'no_buyer',vud_ping_accept:Number(ping?.accept) === 1,vud_ping_recommande:Number(ping?.recommande) === 1,vud_ping_cpl:Number(ping?.cpl)||0,vud_ping_ecpl:Number(ping?.ecpl)||0,vud_ping_buyers:Number(ping?.buyers)||0}); return json({success:true,status:'no_buyer',message:'Votre demande est enregistrée.'},202,origin); }
  try { const mobile = phone.startsWith('06') || phone.startsWith('07'); const body = new URLSearchParams({key:vudApiKey,cat_id:String(catId),nom:String(raw.nom).trim(),prenom:String(raw.prenom).trim(),email:String(raw.email).trim(),tel:mobile?'':phone,mobile:mobile?phone:'',adresse1:String(raw.adresse).trim(),adresse2:'',cp:String(raw.cp),ville:String(raw.ville).trim(),cp_projet:String(raw.cp),ville_projet:String(raw.ville).trim(),pays:'fr',tp:'1',type_bien:String(raw.typeBien||'1'),situation:String(raw.situation||'1'),delais:String(raw.delais||'2'),terrain:'0',permis:'3',description,site_name:SITE_DOMAIN,format_return:'json',matin:'1',midi:'1',soir:'1',we:'0'}); const response = await withTimeout(VUD_LEAD_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body},fetcher); const text = await response.text(); const data = JSON.parse(text); const result = extractVud(data); const status = result.code === '200' ? 'sent' : 'captured'; await patch({vud_status:status,vud_ping_accept:true,vud_ping_recommande:true,vud_ping_cpl:Number(ping.cpl)||0,vud_ping_ecpl:Number(ping.ecpl)||0,vud_ping_buyers:Number(ping.buyers)||0,vud_cpl:Number(ping.cpl)||0,vud_devis_id:result.devisId ? String(result.devisId) : null,vud_devis_hash:result.devisHash,vud_response:data}); return json({success:true,status,devisId:result.devisId},status==='sent'?200:202,origin); } catch { await patch({vud_status:'captured',vud_ping_accept:true,vud_ping_recommande:true}); return json({success:true,status:'captured',message:'Votre demande est enregistrée.'},202,origin); }
}
export const onRequestOptions = ({ request, env }) => { const origin = request.headers.get('Origin') || ''; return isAllowedOrigin(origin,env) ? new Response(null,{status:204,headers:cors(origin)}) : json({success:false,message:'Origine non autorisée.'},403,origin); };
export const onRequestPost = (context) => handleLead(context);
export const onRequest = ({ request }) => json({success:false,message:'Méthode non autorisée.'},405,request.headers.get('Origin') || '');
